---
- name: Add browsers
  homebrew_cask:
    name: [google-chrome, firefox]
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add desktop utility tools
  homebrew_cask:
    name: [dash, alfred, flux, caffeine, spectacle]
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add general desktop tools
  homebrew_cask:
    name: [slack, microsoft-office, dashlane, zoomus]
  when: ansible_os_family == 'Darwin'
  tags: common
